### PR TITLE
Resolve #20.

### LINKED ISSUE #18: Use Authorization header instead of deprecated query string
I just got a mail from GitHub, telling me that they have deprecated the `access_token` query string authentication. A header field should be used instead.

> Please use the Authorization HTTP header instead, as using the `access_token` query parameter is deprecated.

### LINKED ISSUE #20: Migrate to using GraphQL API
You may want to migrate to API version [v4](https://developer.github.com/v4/), which offers a GraphQL interface. Using a GraphQL query, the amount of traffic to be transferred to get the repo size could be reduced dramatically. You would be able to request only the single `size` field, instead of the whole > 100 lines long JSON document for each repo.

### PR DESCRIPTION
**Pull request by n1try**
Also resolves #18 in addition. Merge after #19 and overwrite all merge conflicts with this version. 

Response payload size is now ~ 86 bytes as opposed to ~ 5500 bytes before.

### CODE REVIEW

**Comment by n1try** [comment]
Please note: this requires a token to be specified. Otherwise, `401` is returned and repo size won't be displayed on the page.

**Comment by n1try** [comment]
@Shywim Would you mind taking a quick look at my two PRs?

**Comment by Shywim** [comment]
Sorry for the delay, just went through my mails. Thanks for your PRs ! 😄

**Comment by n1try** [comment]
No worries, thanks! :slightly_smiling_face: 
Are you going to publish a new release to addons.mozilla.org?

**Comment by Shywim** [comment]
It's published and should have already updated :smile:

**Pull request merged**
